### ISSUE TITLE
安装依赖出现各种错误

### ISSUE THREAD

**Issue by yirihan** [liuzhao1225/YouDub#4]
去掉版本号也是不行
Collecting editdistance (from -r requirements.txt (line 58))
  Using cached editdistance-0.6.2.tar.gz (31 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]

**Comment by cslovewl** [comment]
确实，安装依赖各种问题，一上午都没有部署起来。

**Comment by gzq-myy** [comment]
我也是，切换了好几个python版本都不行

**Comment by Virream** [comment]
+1

**Comment by liuzhao1225** [comment]
已经升级`requirements.txt`。

**Comment by Virream** [comment]
> 已经升级`requirements.txt`。

我在cmd中执行pip install -r requirements.txt时遇到了以下错误

ERROR: Ignored the following versions that require a different python version: 1.6.2 Requires-Python >=3.7,<3.10; 1.6.3 Requires-Python >=3.7,<3.10; 1.7.0 Requires-Python >=3.7,<3.10; 1.7.1 Requires-Python >=3.7,<3.10; 1.7.2 Requires-Python >=3.7,<3.11; 1.7.3 Requires-Python >=3.7,<3.11; 1.8.0 Requires-Python >=3.8,<3.11; 1.8.0rc1 Requires-Python >=3.8,<3.11; 1.8.0rc2 Requires-Python >=3.8,<3.11; 1.8.0rc3 Requires-Python >=3.8,<3.11; 1.8.0rc4 Requires-Python >=3.8,<3.11; 1.8.1 Requires-Python >=3.8,<3.11
ERROR: Could not find a version that satisfies the requirement paddleaudio>=1.1.0 (from paddlespeech) (from versions: 0.1.0a0, 0.1.0, 0.2.0, 0.2.1, 1.0.0a0, 1.0.0, 1.0.1, 1.0.2)
ERROR: No matching distribution found for paddleaudio>=1.1.0

然后我访问了https://pypi.org/project/paddleaudio/#files
下载了paddleaudio-1.1.0-cp310-cp310-win_amd64.whl文件
尝试使用pip install命令安装
  首先我在cmd输入python显示Python 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)] on win32
  使用pip install命令安装whl文件显示ERROR: paddleaudio-1.1.0-cp310-cp310-win_amd64.whl is not a supported wheel on this platform.
 然后我又试了试cp39,38,37版都是同样的错误,是我的python版本有兼容性问题吗?又或者是别的什么,我不怎么了解python语言

**Comment by liuzhao1225** [comment]
> > 已经升级`requirements.txt`。
> 
> 我在cmd中执行pip install -r requirements.txt时遇到了以下错误
> 
> ERROR: Ignored the following versions that require a different python version: 1.6.2 Requires-Python >=3.7,<3.10; 1.6.3 Requires-Python >=3.7,<3.10; 1.7.0 Requires-Python >=3.7,<3.10; 1.7.1 Requires-Python >=3.7,<3.10; 1.7.2 Requires-Python >=3.7,<3.11; 1.7.3 Requires-Python >=3.7,<3.11; 1.8.0 Requires-Python >=3.8,<3.11; 1.8.0rc1 Requires-Python >=3.8,<3.11; 1.8.0rc2 Requires-Python >=3.8,<3.11; 1.8.0rc3 Requires-Python >=3.8,<3.11; 1.8.0rc4 Requires-Python >=3.8,<3.11; 1.8.1 Requires-Python >=3.8,<3.11 ERROR: Could not find a version that satisfies the requirement paddleaudio>=1.1.0 (from paddlespeech) (from versions: 0.1.0a0, 0.1.0, 0.2.0, 0.2.1, 1.0.0a0, 1.0.0, 1.0.1, 1.0.2) ERROR: No matching distribution found for paddleaudio>=1.1.0
> 
> 然后我访问了https://pypi.org/project/paddleaudio/#files 下载了paddleaudio-1.1.0-cp310-cp310-win_amd64.whl文件 尝试使用pip install命令安装 首先我在cmd输入python显示Python 3.10.5 (tags/v3.10.5:f377153, Jun 6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)] on win32 使用pip install命令安装whl文件显示ERROR: paddleaudio-1.1.0-cp310-cp310-win_amd64.whl is not a supported wheel on this platform. 然后我又试了试cp39,38,37版都是同样的错误,是我的python版本有兼容性问题吗?又或者是别的什么,我不怎么了解python语言

看看这个能不能帮到你https://github.com/PaddlePaddle/PaddleSpeech#installation

**Comment by lindembergandrade** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
vidhanmangla, @rezarudy, @Maudykaz, @virtualsuccessdev, @MaryamRezazade, @topaccina, @ahoramazdaa, @apianta, @davhud, @RishiKeerthi, @sadityakumar9211, @linux2020, @lowk3v, @Spt117, @davishoang, @zdus4w, @liuzhao1225, @Cypher4300, @Elitsuv, @AmirNasrollahi, @henrimahal, @silaslenihan, @mdeyn, @KunalKaushik2, @kaznak, @hoangkimthu37, @imagineaizy, @MelikNabiOzcan, @cotoneum, @arunadaybasu, @eesilas, @leandroglopez, @ajays97, @OmarMWarraich, @chuanyue98, @mikolajroszak, @HatemSaadallah, @GoesToTwentyOne, @kryptokent, @mattbrc, @Xiaobo2020, @sharmavaibhav059, @kvngdavid, @SunJ3t, @Gopaloraon, @anupamdey2001, @Ajreality1, @baoanh1310, @XiaoNai1987, @simluytPhDr-B, @asimhafeezz, @alexarevalo9, @Al-Baqshi, @Saitejabairu, @vivek-tamilarasan, @karthedew, @JohnsonSmile, @lightnlightning, @Div-Denis, @ehsanshojaeiiii, @DChan0319, @fahust, @anukin, @mhoweis, @york2021, @tamjid0x01, @hrithikk28, @juant72, @devhimal, @Heru2BCrypt, @dthakur1, @nagpalnitesh, @amarinkovic, @Dmdv, @rongzhang, @Tevin-Isaac, @Tomasz5792, @pamisijohn, @LamLarryyyy, @KrzysPi, @ZakariaBashir, @nada-086, @TheACKx, @plamen5rov, @ganemchedli, @dango198, @Eksan03, @hobo71, @Rahul-Prasad-07, @IhorNezdropa, @aelmanaa, @Paigeyuan, @irishikush, @PCWCFA, @hank1755, @amanbthakkar, @Azhar-Bondi, @MannWLA, @kanjih-ciandt
